### ISSUE TITLE
catshare.sh - no premium downlaod

### ISSUE THREAD

**Issue by matchius** [mcrapet/plowshare-modules-legacy#48]
error in premium download:
my workaround: https://github.com/matchius/plowshare-modules-legacy/blob/master/catshare.sh

**Comment by Raziel-23** [comment]
I didn't implement support for premium accounts, because I don't have access to it. Your workaround doesn't work with free accounts. If you don't want create a proper pull request I can prepare a proper solution. I need only one information from you. When you login in to your catshare premium account in upper right corner is a name of account type. You have to give this name. For free accounts there is "Konto: Darmowe". I suspect that premium accounts there is "Konto: Premium", but I'm not 100% sure. In this way I will be able distinguish them.

**Comment by matchius** [comment]
<a href="/premium">Konto: 
                                                                                                                                                                            Premium (<b>30 dni</b>)
                                                                                                                                                                    </a>

My workaround works for no direct download only. 
In catshare you can trun on "direct download"

**Comment by Raziel-23** [comment]
Please check above version, if it works for you I will push it to master. As for "direct download" I don't know what is the difference.

**Comment by Raziel-23** [comment]
Update with cosmetic changes.

**Comment by matchius** [comment]
Code looks great and It works for premium account. 
I haven't tested it for free.

I'm newbie with plownshare and I don't know API, so I couldn't prepere proper solution.
Great job!
Thanks!

**Comment by Raziel-23** [comment]
Final version was pushed to master (again cosmetics changes :)). I tested it for anonymous and free accounts, I only needed a confirmation from you about a premium account. 

When I was writing my first module several months ago (in fact it was catshare module) it was difficult for me to write it. I tried several times, read other modules and finally it began to work. I was lucky because catshare isn't too complicated service. After writing it I wanted to write another module, but I failed :). Recently I wrote a couple of modules and now I have a bit more experience where to look.

It was a bit off topic. Nevertheless thank you for collaboration.
