### ISSUE TITLE
Use Json

### ISSUE THREAD

**Issue by skinner12** [mcrapet/plowshare-modules-legacy#55]
Hello,

I need to extract something from this response that I made with curl:

`FORM UPLOAD: {"status":"success","code":200,"form_action":"http:\/\/81.211.2.116:8000\/upload","file_field":"file","form_data":{"ajax":true,"params":"{\"project\":\"trix\",\"expire\":1455768667,\"extras\":{\"user_id\":11,\"parent_id\":\"\"}}","signature":"04fa32d662324238dfd5fbf3f60087b36d693caf7b1dc8aaf46749a65f63c37fddcd6fb7a1360417d0586566ad635054f002a6f638665d3f77d2dee86ee57"}}
    `

I need to extract `form_data` 

I've tried with:

`formdata=$(parse_json 'form_data' <<< "$FORMUPLOAD" ) || return
    log_debug "FORM DATA RESPONSE: $formdata"`

where $FORMUPLOAD is the response of:

`FORMUPLOAD=$(curl -d '{"auth_token":"'$URL'"}' "$BASE_URL"upload ) || return`

and I get this error:

`parse_json failed (json): "form_data"`

Can anyone help me?

Thanks

**Comment by Raziel-23** [comment]
parse_json doesn't work with complex types, [here are described limitations](https://github.com/mcrapet/plowshare/wiki/Modules#json-parsing).
Here is my solution, first replace all \" with " with the following command:
``` FORMUPLOAD=$(replace_all '\"' '"' <<< "$FORMUPLOAD") || return ```
because parse_json doesn't work with \". Now you cannot parse complex types like form_data, but you can parse simple types like expire with command:
``` FORM_EXPIRE=$(parse_json 'expire' <<< "$FORMUPLOAD" ) || return ```
Hope it will help.

**Comment by skinner12** [comment]
Thanks @Raziel-23 ! It works! 

I spent all the afternoon to find out the solution..

**Comment by mcrapet** [comment]
Originally plowshare is designed to run a lightweight hardware (like ARM9 board.. yeah before Raspberry PI). 
Thinking of a fork (with more dependencies) using [jq](https://github.com/stedolan/jq) and [pup](https://github.com/ericchiang/pup).

**Comment by skinner12** [comment]
Hi,

thanks for suggestion but I prefer let all original as is: I don't want that if I move plowshare to another station I have to install some stuff; I'm sure that I forget it.

I resolved my issue making manually this json string `"form_data":{"ajax":true,"params":"{\"project\":\"trix\",\"expire\":1455768667,\"extras\":{\"user_id\":11,\"parent_id\":\"\"}}"` extracting every single component from the response.

Maybe it's not the best solution, but it works :)

**Comment by Raziel-23** [comment]
@skinner12 You misunderstand what Matthieu said. I'm pretty sure that he was talking about using jq and pup not only in one module, but in the whole plowshare.

@mcrapet Surely it could bring new possibilities and simplifications. For the moment python come to my mind, because [youtube-dl](https://github.com/rg3/youtube-dl) use it, but writing new modules could be more difficult then it's now. I immediately say that I'm not a python expert and I have limited knowledge about python, it was only my loose thoughts.

**Comment by mcrapet** [comment]
@skinner12  is right!

I don't know if it could help but `parse_json` can take a second argument `split` to cut input string a makes parsing easier afterwards.
For example (jheberg module):
```
NAMES=$(parse_json 'hostName' split <<< "$JSON")
```
