### ISSUE TITLE
New module request: ulozto.net

### ISSUE THREAD

**Issue by knutshub** [mcrapet/plowshare-modules-legacy#56]
Hi developers and associated members,
thanks for this nice too. I would appreciate a new script for the hoster: ulozto.net

They are using Captchas and they doesn't have an API. Download (and maybe Upload) functionality would be fine.

**Comment by Raziel-23** [comment]
In my free time I can implement download and probe. I can't speak about uploading, maybe in the future or maybe someone else do it. For now I don't touch uploading because:
- I have an asymmetrical connection and my upload speed is significant slower then download speed, thus I will not be able to test uploading very large files
- also this is a new area for me and it can take time before I will be confident during implementation uploading
- also I have to admit that there are more downloaders then uploaders, that's why from my perspective downloading has a higher priority

I don't say no about uploading, but I have to have time to read wiki and other modules in order to understand how it works.

**Comment by Raziel-23** [comment]
If you have access to a premium account then I can add support for it. If you need also uploading support then open another issue, maybe someone will implement it.

**Comment by knutshub** [comment]
Thanks a lot for your help!

**Comment by Raziel-23** [comment]
One note. They have a crappy captcha system. Sometimes we can get a corrupted captcha image, and sometimes when we resolve captcha correctly it is counted as 'Wrong captcha' because for an unknown reason we get from the server an error message after sending resolved captcha: 'The time has run out. Please, send the form again.'.

I can't do anything with it. It not only occurs in this module, but also in a webbrower (when I resolve captcha correctly it is reloaded to another one).
