### ISSUE TITLE
New Module openload.co , upload module

### ISSUE THREAD

**Issue by rlsblogse** [mcrapet/plowshare-modules-legacy#74]
hi,
please can u make a upload module of openload.co  it has a API. see below.

https://openload.co/api

regards

**Comment by Raziel-23** [comment]
You will have to wait, depending on a service's complexity it takes time to write new module. I already like this service, devs have a humor :laughing:
```
$ curl https://api.openload.co/1
Congratulations! You have found an empty page! Go celebrate this great discovery by sending the admin a coffee (or a beer...)
```

**Comment by Raziel-23** [comment]
I hope that you already use plowshare core version 2.1.3, because in this module I desperately needed a new return code.

**Comment by Raziel-23** [comment]
I forgot to mention that this uploading support is implemented in openload_io module, because openload.co and openload.io this is the same service. Maybe module name should be changed, because we are redirected from openload.io to openload.co. I made a little mistake during writing commit message https://github.com/mcrapet/plowshare-modules-legacy/commit/e70155c1368f1ab8f21cf6fd5240d00fa3a3edc9, there should be openload_io instead of openload_co.
