### ISSUE TITLE
uploadable.ch Rebranded to bigfile.to

### ISSUE THREAD

**Issue by 0xbzho** [mcrapet/plowshare-modules-legacy#86]
This [patch](https://github.com/0xbzho/plowshare-modules-legacy/commit/b1a50f970f1437b9d2986bd62dbe17e039dea684) fixes anonymous download for me, but could use testing by somebody with an account/folders.

**Comment by Raziel-23** [comment]
Thank you for reporting this issue and for your patch. I will check it and probably extend it. This module probably needs more refactoring. I will also rename a module name to bigfile.

P.S. You will have to wait with your pull requests for Matthieu. He definitely has more knowledge/experience then me. Also I'm not good collaborator because I'm too strict person :D.
