### ISSUE TITLE
Parse Error (sed)

### ISSUE THREAD

**Issue by normanfeltz** [mcrapet/plowshare-modules-legacy#94]
Hey, 

I have a error on launch :
`parse_attr failed (sed): "//d// href="
Failed inside uptobox_download(), line 166, uptobox.sh`

Cordialy

Norman FELTZ

**Comment by Raziel-23** [comment]
You are using a premium account on uptobox. I don't have access to a premium account on uptobox, so in order to fix this you will have to give me access to your account. You can send me an email with login and password. If you don't want give me access to it, then I will need some sort of cooperation from your side.

**Comment by shins5kai** [comment]
i have the same issue ^^

**Comment by shins5kai** [comment]
email me : seby63 at hotmail.fr
